title = '犀谭'
baseURL = 'https://ariesnine.cn/'
languageCode = 'en-us'
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] 

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
    disable = false

[services]
  [services.googleAnalytics]
    id = 'G-J0PQS7E9QS' 

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[menu]
  [[menu.main]] 
    pageRef="/"
    name = '主页'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="技术"
    name = '技术'
    url = '/技术/'
    weight = 20
  [[menu.main]]
    pageRef="工具"
    name = '工具'
    url = '/工具/'
    weight = 30
  [[menu.main]]
    pageRef="应用"
    name = '应用'
    url = '/应用/'
    weight = 40
  [[menu.main]]
    pageRef="杂谈"
    name = '杂谈'
    url = '/杂谈/'
    weight = 50
  [[menu.main]]
    pageRef="其他"
    name = '其他'
    url = '/其他/'
    weight = 60
  [[menu.main]]
    pageRef="about"
    name = '关于'
    url = '/about/'
    weight = 70

[params]
  sitename = "sitename"
  defaultColor = "dark" 
  description = "The Universe in a Shell"

[params.author]
  avatar = "avatar.png"
  intro = "The Universe in a Shell"
  name = "Rhino Nine"
  description = "Another Day Another Code"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Rhino-Nine"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
