title = '犀谭'
baseURL = 'https://ariesnine.cn/'
languageCode = 'en-us'
enableEmoji = true
ignoreErrors = ["additional-script-loading-error"] 

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
    # disable = true

[services]
  [services.googleAnalytics]
    id = 'G-J0PQS7E9QS' 

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true
	[markup.tableOfContents]
		startLevel = 2 # ToC starts from H2
		endLevel = 4 # ToC ends at H4
		ordered = false # generates <ul> instead of <ol>

[menu]
  [[menu.main]] 
    pageRef="posts"
    name = '文章'
    url = '/posts/'
    weight = 10
 [[menu.main]] 
    pageRef="dreams"
    name = '梦匣'
    url = '/dreams/'
    weight = 20
 [[menu.main]]
    pageRef="categories"
    name = '分类'
    url = '/categories/'
    weight = 30
   [[menu.main]]
    pageRef="tags"
    name = '标签'
    url = '/tags/'
    weight = 40
  [[menu.main]]
    pageRef="about"
    name = '关于'
    url = '/about/'
    weight = 50

[taxonomies]
tag = "tags"
category = "categories"

[params]
  sitename = "sitename"
  defaultColor = "dark" 
  description = "The Universe in a Shell"

[params.author]
  avatar = "avatar.png"
  intro = "The Universe in a Shell"
  name = "Rhino Nine"
  description = "Another Day Another Code"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Rhino-Nine"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"
